<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="audiofile\Dance_Of_The_Dream_Man.mp3" />
    <None Remove="audiofile\Sherlock_Theme.mp3" />
    <None Remove="audiofile\Twin_Peaks_Theme.mp3" />
    <None Remove="nots.png" />
    <None Remove="View\image\back.png" />
    <None Remove="View\image\filledLike.png" />
    <None Remove="View\image\forward.png" />
    <None Remove="View\image\library.png" />
    <None Remove="View\image\like.png" />
    <None Remove="View\image\myLike.png" />
    <None Remove="View\image\playPause.png" />
    <None Remove="View\image\user.png" />
    <None Remove="View\image\vinyl.png" />
    <None Remove="View\image\vol.png" />
    <None Remove="View\image\volmute.png" />
    <None Remove="View\nots.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="audiofile\Dance_Of_The_Dream_Man.mp3" />
    <Resource Include="audiofile\Sherlock_Theme.mp3" />
    <Resource Include="audiofile\Twin_Peaks_Theme.mp3" />
    <Resource Include="nots.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="View\image\back.png" />
    <Resource Include="View\image\filledLike.png" />
    <Resource Include="View\image\forward.png" />
    <Resource Include="View\image\library.png" />
    <Resource Include="View\image\like.png" />
    <Resource Include="View\image\myLike.png" />
    <Resource Include="View\image\playPause.png" />
    <Resource Include="View\image\user.png" />
    <Resource Include="View\image\vinyl.png" />
    <Resource Include="View\image\vol.png" />
    <Resource Include="View\image\volmute.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
